spring.application.name=career-connect

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/career_connect
spring.datasource.username=postgres
spring.datasource.password=Niveditha$28

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5-mini

# Logging
logging.level.org.springframework.security=INFO

# JWT
jwt.secret=${JWT_SECRET}